
server:
  port: 8887

spring:
  main:
    banner-mode: off
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot_tb?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSl=false
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      # 表前缀
      table-prefix: tb_
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将下划线映射到驼峰大小写
    map-underscore-to-camel-case: true
